### ISSUE TITLE
Consider integration with nivo

### ISSUE THREAD

**Issue by lordjabez** [awslabs/green-boost#131]
Nivo is a collection of components for rich data visualization. https://nivo.rocks/

**Comment by bestickley** [comment]
@lordjabez, thanks for bringing this library to my attention. I like how nivo is React specific and allows customizations directly through props and server side rendering is a nice perk. However, the current data visualization library used for GB ([amCharts5](https://www.amcharts.com/)) has a lot more functionality built in out of the box, more demos to learn from, and better documentation IMO. A developer is welcome to use nivo in a GB project/template, but official dashboard components will likely continue to use amCharts.

Please reopen if you still have questions.
