### ISSUE TITLE
Error on ESLint First Run

### ISSUE THREAD

**Issue by bbenjon** [awslabs/green-boost#162]
When Running gboost create with any input, the first run of eslint always causes an error because the path given is wrong, but the error message is at the end, and makes it seem like the process for gboost fails. 

```
. prepare$ husky install
│ husky - Git hooks installed
└─ Done in 281ms

Oops! Something went wrong! :(

ESLint: 8.29.0

No files matching the pattern "src/**/*.{ts,tsx}" were found.
Please check for typing mistakes in the pattern.

An error occurred :(
```

**Comment by bestickley** [comment]
Thank you for reporting this @bbenjon! We'll prioritize this fix and keep you updated.

**Comment by bestickley** [comment]
Closing as OP said in PR:
> Unable to recreate issue with newest version. Closing this PR.
